### ISSUE TITLE
No Requirements.txt

### ISSUE THREAD

**Issue by yasanthaniroshan** [yasanthaniroshan/Total-Watch-Time#2]
Since above script is using movieeditor there may some imported modules

**Comment by chathura-de-silva** [comment]
_Here is a simple readme if you are into that._

# Watchtime Calculation Script

This script helps estimate the total time spent watching video lectures within a specified folder. It can be useful for students to monitor their study habits.

## How to Use

1. **Run the Script**: Execute the script in your Python environment.

2. **Input Folder Path**: You will be prompted to enter the path of the folder containing your video files.

3. **Results**: The script will process the video files in the folder and provide the total watch time in minutes.

## Supported File Formats

Make sure your video files have one of the following extensions: `.mp4`, `.avi`, `.mkv`, `.mov`, `.wmv`, or `.flv`.

## Requirements

Make sure you have the following installed before running the script:

- Python
- `moviepy` library

## Running the Script

To run the script, execute the Python script provided. Follow the prompts to input the path of your main folder.

## Note

If there are any issues or errors during the process, the script will display a corresponding error message.

```markdown
# Watchtime Calculation Script

This script helps estimate the total time spent watching video lectures within a specified folder. It can be useful for students to monitor their study habits.

## How to Use

1. **Run the Script**: Execute the script in your Python environment.

2. **Input Folder Path**: You will be prompted to enter the path of the folder containing your video files.

3. **Results**: The script will process the video files in the folder and provide the total watch time in minutes.

## Supported File Formats

Make sure your video files have one of the following extensions: `.mp4`, `.avi`, `.mkv`, `.mov`, `.wmv`, or `.flv`.

## Requirements

Make sure you have the following installed before running the script:

- Python
- `moviepy` library

## Running the Script

To run the script, execute the Python script provided. Follow the prompts to input the path of your main folder.

## Note

If there are any issues or errors during the process, the script will display a corresponding error message.
```

**Comment by yasanthaniroshan** [comment]
thanks Buddy !
